#!/usr/bin/env python3
"""
Merge supplement_questions.json into questions.json.

Reads:
    data/questions.json           (base — generated by parse-pdfs.py)
    data/supplement_questions.json (generated by parse-supplement.py)

Writes:
    data/questions.json           (with supplement questions appended,
                                   questionCount updated per category)
"""

import json
import os
import sys
from collections import Counter

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_PATH = os.path.join(SCRIPT_DIR, "..", "data", "questions.json")
SUPP_PATH = os.path.join(SCRIPT_DIR, "..", "data", "supplement_questions.json")


def main():
    if not os.path.isfile(BASE_PATH):
        print(f"ERROR: {BASE_PATH} not found — run parse-pdfs.py first", file=sys.stderr)
        sys.exit(1)
    if not os.path.isfile(SUPP_PATH):
        print(f"ERROR: {SUPP_PATH} not found — run parse-supplement.py first", file=sys.stderr)
        sys.exit(1)

    with open(BASE_PATH, encoding="utf-8") as f:
        base = json.load(f)
    with open(SUPP_PATH, encoding="utf-8") as f:
        supp = json.load(f)

    base_questions = base["questions"]
    base_ids = {q["id"] for q in base_questions}

    supp_questions = supp["questions"]

    # Drop any prior supplement entries from base (idempotent re-merge)
    base_questions = [q for q in base_questions if not q.get("supplement")]
    base_ids = {q["id"] for q in base_questions}

    # Sanity: no ID collision (supplement IDs use the "S" prefix)
    collisions = [q["id"] for q in supp_questions if q["id"] in base_ids]
    if collisions:
        print(f"ERROR: ID collisions: {collisions[:5]}", file=sys.stderr)
        sys.exit(1)

    merged_questions = base_questions + supp_questions

    # Recompute questionCount per category
    counts = Counter(q["categoryId"] for q in merged_questions)
    for cat in base["categories"]:
        cat["questionCount"] = counts.get(cat["id"], 0)

    base["questions"] = merged_questions

    with open(BASE_PATH, "w", encoding="utf-8") as f:
        json.dump(base, f, ensure_ascii=False, indent=2)

    base_count = sum(1 for q in merged_questions if not q.get("supplement"))
    supp_count = sum(1 for q in merged_questions if q.get("supplement"))
    print(f"Merged: {base_count} base + {supp_count} supplement = {len(merged_questions)} total")
    print()
    print("Per category:")
    for cat in base["categories"]:
        cid = cat["id"]
        s = sum(1 for q in merged_questions if q["categoryId"] == cid and q.get("supplement"))
        b = cat["questionCount"] - s
        print(f"  {cid}. {cat['name']}: {cat['questionCount']} (base {b} + supplement {s})")


if __name__ == "__main__":
    main()
